### ISSUE TITLE
Support Shiki Fine-grained Bundles

### ISSUE THREAD

**Issue by JonasHiltl** [expressive-code/expressive-code#251]
When deploying an Astro site using `expressive-code` (via `astro-expressive-code`) to Cloudflare Workers, the bundle size exceeds the 1MB limit imposed by Cloudflare's free plan. This happens because `expressive-code` includes all built-in languages and themes from Shiki by default, with no option to reduce the included languages.

It would be nice to specify only the required languages and themes and use Shiki's [fine-grained bundle](https://shiki.style/guide/bundles#fine-grained-bundle) approach under the hood.

I also tried writing my own `shiki-plugin`, using a fine-grained bundle with the `createHighlighterCore` function and disabling `shiki` in the `expressive-code` config but the bundle still includes all languages and themes.
I think that's caused because [expressive-code](https://github.com/expressive-code/expressive-code/blob/main/packages/expressive-code/src/index.ts#L9) includes this:
```js
export * from '@expressive-code/plugin-shiki'
```

**Comment by hippotastic** [comment]
Hello and welcome @JonasHiltl! Thank you for this feature request and sorry it took me a while to reply!

I absolutely agree that EC shouldn't increase your bundle size so much and we need to do something about this. The current package structure wasn't designed with SSR and the need for granular bundles in mind.

It's awesome to hear that you already tried to experiment with creating a `plugin-shiki` version using a fine-grained bundle yourself!

Could you maybe share a small reproduction that includes your modified version of `plugin-shiki` and still hits the bundle size limit due to the export you mentioned? I'd love to experiment a bit with that and see if I can come up with an approach to make the bundle smaller.

If creating a reproduction would be too much work, I just want to share what I wanted to try: I'd attempt to use pnpm's overrides feature to deep replace the default `@expressive-code/plugin-shiki` package with your modified version. I'd be curious to see if something like that is feasible. Of course I'm also open to other ideas.

**Comment by JonasHiltl** [comment]
@hippotastic Here is a repro https://github.com/JonasHiltl/expressive-code-repro.

This doesn't hit the 2MB limit but it's still around 660MB and includes all the built in languages, even though I used the fine-grained bundle approach from shiki.

**Comment by hippotastic** [comment]
I experimented a bit more and removed the adaptations you made in your reproduction to get as close to a Starlight default project as possible: I re-enabled the shiki plugin, removed the custom one, removed the `markdown.shikiConfig` options, rebuilt the site, ran the preview. Most of the bundle size is not coming from EC.

There must be an important difference between your reproduction and your actual repo that's hitting the size limit that we are still missing.

**Comment by hippotastic** [comment]
Ohh, I think I found something:

This seems to be a tree shaking issue. As soon as I add any import from `@astrojs/starlight/components` to the `index.mdx` file, the bundle size increases drastically. Even if I only do `import { Tabs } from '@astrojs/starlight/components'`, all Starlight components including all of their dependencies get pulled into the bundle, no matter if they are actually being used or not.

All the Shiki languages and themes that previously contained `// Contents removed by Astro as it's used for prerendering only` now contain their actual content. Apparently, Astro is no longer able to recognize that these files are unused.

However, even after removing the line `export { Code } from 'astro-expressive-code/components';` from Starlight's `components.ts`, the bundle is still above 1 MB due to the size of Starlight's other components and their dependencies, especially `LinkButton` that is over 1 MB alone already.

**Comment by hippotastic** [comment]
Ok, so I wrote a small Astro integration that does exactly what I described above: It removes all unwanted languages and themes from the Shiki bundle. You can just modify the `allowedAssets` const to configure it.

In your Astro config file, add this into your `integrations` array below Starlight itself:

```js
{
  name: 'trim-shiki',
  hooks: {
    'astro:config:setup': ({ updateConfig }) => {
      updateConfig({
        vite: {
          plugins: [
            {
              name: 'vite-plugin-trim-shiki',
              transform: (code, id) => {
                const allowedAssets = {
                  langs: ['javascript', 'yaml'],
                  themes: ['houston'],
                };

                const pathRegExp = /\/shiki\/dist\/(langs|themes)\.m?js$/;
                const assetType = id.match(pathRegExp)?.[1];
                if (!assetType) return;

                const entryRegExp =
                  /(?<=\n)\s*\{[\s\S]*?"id": "(.*?)",[\s\S]*?\n\s*\},?\s*\n/g;
                return code.replace(entryRegExp, (match, id) => {
                  if (allowedAssets[assetType].includes(id)) return match;
                  return '';
                });
              },
            },
          ],
        },
      });
    },
  },
},
```

After this change, all the unwanted files will be gone - effectively reaching your goal of a fine-grained bundle. However, this still doesn't get Starlight below 1 MB when using any of the components, and we would need more non-EC related trimming logic to achieve this goal.

**Comment by JonasHiltl** [comment]
Wow! Thanks for doing so much and the vite plugin works great. 
I also removed all imports from `@astrojs/starlight/components` in my actual project and now my bundle is small enough.

Since the issue wasn’t related to EC but rather to Starlight's components, this can now be closed.

**Comment by hippotastic** [comment]
Just FYI, support for fine-grained bundles is now built into `astro-expressive-code`. I've just released [version 0.39](https://expressive-code.com/releases/#0390) to NPM that includes multiple new config options focused on SSR bundle trimming.

Starlight will also be updated soon to include this new version of Expressive Code.

Thanks again for the request! :)

**Comment by Nicceboy** [comment]
Hi, amazing library! Would fine-grained bundling be complicated to integrate into `rehype` as well?

**Comment by hippotastic** [comment]
> Hi, amazing library! Would fine-grained bundling be complicated to integrate into `rehype` as well?

Thank you! Unfortunately, the approach I used in the Astro integration (which uses a custom Vite plugin to rewrite the imports on the fly) can't be replicated in the Rehype integration as I can't even rely on Vite being present in the toolchain at all.

Now that Shiki offers a custom bundle generator on their website, I could imagine that you can create your own bundle including only the themes and languages you need, add it to your project, and use your package manager's `overrides` feature in `package.json` to replace the Shiki package imported by `plugin-shiki` with your custom bundle. I didn't test this approach, but in theory it should work!

**Comment by Nicceboy** [comment]
Thanks for the reply! I will look into this.
