### ISSUE TITLE
Bug: ins attributes only highlights last line number in list

### ISSUE THREAD

**Issue by techthumb** [expressive-code/expressive-code#274]
```astro
---
import {Code} from "astro-expressive-code/components";
const code = `line one
line two 
line three
line four
line five
line six
line seven
line eight
line nine
line ten`;
---

<html lang='en'>
<body>
<Code code={code} ins={1,3,5}/>
</body>
</html>

```

![Screenshot 2024-11-12 at 15 20 17](https://github.com/user-attachments/assets/f8314dbc-44f4-4557-9228-14f84387f32a)

**Comment by hippotastic** [comment]
Hello! As you're using JSX syntax here, you actually forgot to make it a list. :) 

You need to use the array syntax, so `{[1, 3, 5]}`.

**Comment by techthumb** [comment]
Got it, thanks. That worked well.

Is there a way to specify a range?

```
<Code code={code} ins={[1-3, 6]}/>
```

**Comment by hippotastic** [comment]
What you're aiming for is not possible directly in JSX, as it would perform a calculation instead of actually specifying a range.

To work around this issue, the `<Code>` component has a `meta` prop that allows you to use exactly the same syntax as you normally would in the meta information after an opening code fence. Applying this to your example code, the working version would look like this:

```astro
<Code code={code} meta="ins={1-3, 6}" />
```

I'm sorry if this is confusing, I realize that the necessary changes between the syntax used in fenced code blocks and the syntax used in `<Code>` component props aren't explained in enough detail in my docs. I'll add some more explanations and examples.
