### ISSUE TITLE
Feature: Number of Lines 

### ISSUE THREAD

**Issue by robsongajunior** [expressive-code/expressive-code#37]
I would like a lot to have an option on components to be possible to show the number of lines in the left side of code block.

![Screenshot 2023-07-19 at 15 55 51](https://github.com/expressive-code/expressive-code/assets/3317013/8d313508-e24a-403c-90f6-6f37a7b9fe1c)
In the image we have the example of code block.

**Comment by hippotastic** [comment]
Hello @robsongajunior, thank you for this feature request! Adding a config option to enable line numbers sounds like a good idea to me.

Would you like to enable line numbers for all code blocks on your site, or only some of them?

**Comment by robsongajunior** [comment]
Thanks for you attention @hippotastic!

Hmmm, good question! I believe it is interesting not at all, because sometimes we want to simulate a terminal command and terminal does not have number lines, but when it is real code example simulating ide should be great at all.

**Comment by hippotastic** [comment]
Right, good point! I think the terminal window style should never need line numbers. I'll make sure that they only appear in editor windows when enabled.

**Comment by robsongajunior** [comment]
Exactly! Sounds good.
On Weekend i will try to learn how the project works to help develop and improve the features

**Comment by HenestrosaConH** [comment]
I came to the issues pages to ask exactly what OP said. It would be nice to enable lines in the code similar to what [Rehype](https://rehype-pretty-code.netlify.app/) does with the `showLineNumbers` meta string.

**Comment by dbanty** [comment]
Adding on to this (though if it's a follow-up, that's okay too), we should be able to specify which line to _start_ at in case we're showing only part of the file. You could also use the collapsible lines plugin, but you might not always want to include so much.

**Comment by hippotastic** [comment]
Hello @dbanty and welcome! Thank you for the great follow-up. I like the idea of being able to specify a starting line number.

Sorry that I haven't gotten to implementing this feature request yet. I'm currently finishing a huge architectural change that allows very efficient multi-theme rendering without duplicating the HTML output, all thanks to the power of CSS variables. After this is done, I'll be able to focus on the pending feature requests again.

Thanks everyone for your patience!

**Comment by mehalter** [comment]
Hey! Love this package and it's rendering of code blocks. Just to add my two cents as someone who has used a countless number of markdown rendering libraries/typesetting packages.

- When it comes to specifying which code blocks show line numbers or not it will really fall into use case and the user's preference. Markdown renderers that I have like previously will take the model of being able to set the default as well as using a keyword/setting in the code block if you want to specifically override the default. Some people may prefer "line number default, but not 100% of the time" and others might prefer the other.
- I do also like the idea of configuration at the frame level as well. As previously mentioned the terminal frame doesn't necessarily make sense to have line numbers but there *could* be a case where a user is writing to describe the lines in the terminal frame and simply want them to be able to reference "as we can see in line 4..." type stuff. I honestly haven't gone too deep into configuring frames so maybe having just frame level configuration of the default line number on/off is even enough rather than a completely global on/off default control.
- I agree that specifying the starting line number is a phenomenal idea. It could also be great to be able to use the frame to indicate there are lines above and/or below like a line at the beginning or end that look like `...` or something. It is nice to indicate to the user visually "this isn't the entire file nor is this necessarily the end of the file"

Again thanks to everyone involved for all the work that has gone into this, especially @hippotastic for getting this into Astro Starlight recently!

**Comment by hippotastic** [comment]
> @hippotastic could you give me a hint as where to start implementing this? I'd like to give it a shot. I've been looking through the source but still unsure where the starting point for this would be best

First of all, thank you for offering help on this! For me, the hardest part in this feature request is actually coming up with working HTML & CSS code (without any JS) that achieves an appearance & behavior similar to VS code:
- The line numbers and possible gutter icons (like +/- diff markers or expand/collapse icons from the collapsible sections plugin) always stay on the left border of the code block while the rest of the code can be scrolled horizontally if it's overflowing the frame.
- The line numbers stay in sync with the code lines, even if the code line wraps across multiple lines (a feature which we already have a [feature request](https://github.com/expressive-code/expressive-code/issues/98) for and that should be taken into account when finding a new HTML structure)
- It is possible to change the background color of individual lines to implement line highlighting in the text markers plugin.

I'd gladly take care of implementing this in EC once I have the HTML & CSS that ticks all the boxes above. Maybe there is some existing solution somewhere that we could take as a basis?

**Comment by vasfvitor** [comment]
Well... now I see why you haven't implemented XD
https://codepen.io/reatorforvi/pen/gOqqmpX
Later I'll do another quick research and give another shot at it after reading the css counter specs. So far this is what I came up with and I'm sure you already have this.
