### ISSUE TITLE
control over how the styles are loaded

### ISSUE THREAD

**Issue by mayank99** [expressive-code/expressive-code#57]
Hi, thanks for making this awesome package!

It looks like `astro-expressive-code` will automatically manage how styles are loaded. I use [cascade layers](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers) for managing all my styles, so I would like to be able to put all third-party styles within a specific cascade layer.

Would it be possible to allow disabling the default style injection and instead expose the stylesheet for manually importing? I'm thinking a config option + a new package entrypoint for the `.css`.

Happy to contribute if I can.

**Comment by hippotastic** [comment]
Hi and welcome @mayank99, glad to have you here!

I'd love to offer an option that allows to use cascade layers for Expressive Code as well.

Exposing the stylesheets as `.css` files is unfortunately not as simple as I'd like due to the dynamically generated nature of the stylesheets which inject theme colors, feature-dependent blocks, user overrides, use SASS-like nesting etc. Therefore, instead of diving into this challenge (which we could definitely do at some point, but it's going to be tricky), I'd like to explore other options first that could still allow you to use cascade layers.

Here are a couple of options I could think of right now:
1. We could add a config option like `cascadeLayer` that, when defined, wraps all of the dynamically injected CSS into a `@layer <cascadeLayer>` at-rule block. You could then ensure in your site-wide CSS that the layers are ordered the way you want them to.
2. We could add a config option to `astro-expressive-code` that outputs all dynamically generated core & plugin base styles into CSS file in a location of your choice, instead of injecting it into the rendered HTML output. This could be an actual CSS file in the `public` folder, or a file route created through Astro's `injectRoute` API. You could then use `@import <url> <layer>` in your site-wide CSS to add the contents to your preferred layer.
   - Note: This would probably force us to abandon the `addStyles` API that currently allows plugins to dynamically add styles when a particular feature is actually being used on the page. I haven't used this feature yet, and I'm not sure if it's worth keeping due to its added complexity, so I'd be willing to sacrifice that to pave the way for better options to customize Expressive Code's CSS.

Would any of these work for you, and/or do you have other ideas as well? Happy to discuss!

**Comment by mayank99** [comment]
Thanks for so promptly considering this request!

So I think a `cascadeLayer` config option would satisfy my use case right now and is definitely simpler. In general though, I think it would be nice to explore providing a way to manually import it, just for more advanced cases like critical styles, preloading, or even something weird like excluding this stylesheet when a `Save-Data` header is found in the request. (these are theoretical use cases that I do not currently have).

The problem with `public` folder I think is that the CSS will not be passed into Vite's PostCSS pipeline for further transformations. Not sure if the same problem happens with `injectRoute`.

I'm not familiar with the `addStyles` api; looks like it only exists in the core package rather than in the astro wrapper? I'm all about simplicity if there isn't much downside. The main downside I can see is slightly larger bundles if a feature is not used? Worth the sacrifice to achieve simplicity imo.
